pipeline {
    agent { docker { image 'python:3.5.1' } }
    stages {
        stage('Get Version') {
            steps {
                sh 'python --version'
            }
        }
        stage('Setup') { // Install any dependencies you need to perform testing
            steps {
                script {
                sh """
                pip install -r requirements.txt
                """
                }
            }   
        }
        stage('Linting') { // Run pylint against your code
            steps {
                script {
                sh """
                pylint **/*.py
                """
                }
            }
        }
        stage('Unit Testing') { // Perform unit testing
            steps {
                script {
                    sh """
                    python -m unittest discover -s tests/unit
                    """
                }
            }
        }
        
    }
}
